=== mrpouet/chenilles/data/maps/map.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT map (informations, layer*)>
<!ELEMENT informations (author, name, description?)>
<!ELEMENT layer (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST layer type (background|ground|explosion) #REQUIRED>

=== mrpouet/chenilles/data/maps/SceneOfCrime_medium/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "../map.dtd">
<map>
  <informations>
    <author>PILLEBOUE Adrien (necropotame)</author>
    <name>SceneOfCrime</name>
    <description>The first map of chenille</description>
  </informations>
  <layer type="background">background.png</layer>
  <layer type="ground">main.png</layer>
  <layer type="explosion">explosion.png</layer>
</map>

=== mrpouet/chenilles/data/maps/testMap1/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "../map.dtd">
<map>
  <informations>
    <author>PILLEBOUE Adrien necropotame</author>
    <name>testMap1</name>
    <description>A simple test map, cool, suxe, and funny</description>
  </informations>
  <layer type="background">background.png</layer>
  <layer type="ground">main.png</layer>
  <layer type="background">foreground.png</layer>
  <layer type="explosion">explosion.png</layer>
</map>
